---
- name: Install and configure tmux 
  hosts: all
  become: true

  tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: true
  
  - name: Install tmux
    ansible.builtin.apt:
      name: tmux
      state: present
